config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#new'

  resources :users
  resource :session

  namespace :api, defaults: { format: :json } do
    resources :users
  end

  get '/about', :to => 'static_pages#about', as: :about_page
  get '/contact', :to => 'static_pages#contact', as: :contact_page

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :session_token, presence: true
  validates :email, :session_token, uniqueness: true

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(user_params)
    user = User.find_by_email(user_params[:email])
    user.try(:is_password?, user_params[:password]) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end


  protected

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController

  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    def create
      @user = user.new(user_params)

      if @user.save
        render json: @user
      else
        flash[:notice] = "Invalid user! Please Try Again"
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    def show
      @users = User.all
      @user = User.find(params[:id])
      @current_user = @user
      render :show

    end

    def index
      @users = User.all
      @current_user = current_user
      user_token = session[:session_token]
      @user = current_user
      render :index
    end

    def edit
      @user = User.find(params[:id])
      render :edit
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        render :json => @user
      else
        render :json => @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    def destroy
      @user = user.find(params[:id])
      @user.destroy
      render :json => {}
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :lat, :lng)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in!(user)
    @current_user = user
    session[:token] = user.reset_token!
  end

  def sign_out!
    current_user.try(:reset_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to users_url
    end
  end

  def create
    if current_user
      redirect_to users_url
    else
      @user = User.find_by_credentials(params[:user])

      if @user
        sign_in!(@user)
        @user.update(lat: params[:user][:lat])
        @user.update(lng: params[:user][:lng])
        redirect_to users_url
      else
        flash.now[:errors] = ["Invalid email and/or password"]
        render :new
      end
    end
  end

  def destroy
    sign_out!
    redirect_to new_session_url
  end

  def session_params
    params.require(:user).permit(:email, :password, :lat, :lng)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!, only: [:root]

  def about
    render :about
  end

  def contact
    render :contact
  end

  def root
    render :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if signed_in?
      redirect_to users_url
    end
  end

  def create
    if signed_in?
      redirect_to users_url
    else
      @user = User.new(user_params)

      if @user.save
        sign_in!(@user)
        redirect_to users_url
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    end
  end

  def update
  end

  def index
    @users = User.all
  end

  def show
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :lat, :lng)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="col-xs-2 col-xs-offset-4">
        <p><a href="">Privacy Policy</a></p>
        <p><a href="">Terms and Conditions</a></p>
        <p><a href=""> @ Copyright Policy</a></p>
    </div>
    <div class="col-xs-2">
        <p><a href="">Home</a></p>
        <p><a href="">About</a></p>
        <p><a href="">Contact</a></p>
    </div>
    <div class="col-xs-2">
        <p><a href="">Press</a></p>
        <p><a href="">Blog</a></p>
        <p><a href="">Invite a Friend</a></p>
    </div>

    <div class="social-media">
        <p>Follow Us!</p>
          <span><i class= "fa fa-twitter-square"></i></span>
          <span><i class= "fa fa-facebook-square"></i></span>
          <i class= "fa fa-google-plus-square"></i>
          <i class= "fa fa-google-plus-square"></i>
          <i class= "fa fa-github-square"></i>
          <i class= "fa fa-pinterest-square"></i>
          <i class= "fa fa-linkedin-square"></i>
          <i class= "fa fa-tumblr-square"></i>

        </ul>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    </div>


<!-- main navbar on top of page-->
<div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">
  <ul class="nav navbar-nav nav-pills nav-links">
    <li><a class="navbar-brand" href="<%= new_user_url %>"><img src= "https://lh3.ggpht.com/vJm9h4jWqOiMliWmd20RTY52i2evyZwSlmny1A7V3dlyH-GuFV-8YIIaH9RegBOsx8g=w300" id="findmyfriends_logo"> FindFriends </a></li>

    <li><a href="<%= about_page_url %>" class="navbar-link">About</a></li>
    <li><a href="<%= contact_page_url %>" class="navbar-link">Contact</a></li>

    <% if current_user %>
      <li><a href="<%= user_url(current_user) %>" class="navbar-link">My Profile</a></li>
      <li><a href="<%= users_url %>" class="navbar-link">MyFriends</a></li>
    <% end %>

  </ul>
</div>



  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
    <% if signed_in? %>
    <!-- dropdown button-->
    <div class="dropdown pull-right">
      <button class="btn btn-primary dropdown-toggle user-drop-down"
              type="button"
              id="user-drop-down"
              data-toggle="dropdown">
              <%= current_user.email %>
              <span class="caret"></span>
      </button>

      <!-- items in the dropdown-->
       <ul class="dropdown-menu"
          role="menu"
          aria-labelledby="dropdownMenu1">
        <li>
          <a href="#" id="my-boards">
          <i class="glyphicon glyphicon-user"></i> My Boards
          </a>
        <li>
          <%= link_to "Sign out", session_url, method: :delete %>
        </li>
      </ul>
    </div>

    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    </ul>
    <% end %>
  </div>
</div>
</nav>





<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>") %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FindFriends</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>">
  </script>
</head>
<body>

  <%= render partial: "layouts/header" %>
  <%= yield %>
  <!-- <%= render partial: "layouts/footer" %> -->

</body>
</html>

<script>
window.current_user_id = <%= current_user.id if current_user %>
</script>

app/views/static_pages/about.html.erb
<br>
<br>
<br>
<div class="col-xs-4 col-xs-offset-4">
<h1>About Us</h1>
<p class="about-us" style="text-align: center; font-size: large;">
  This website allows users to find their Facebook friends
  in real time and view it on a map. Now you can know immediately which of your friends are nearby!
</p>
</div>

app/views/static_pages/contact.html.erb
  <h1>Contact Us</h1>
 <h4>Please fill out this form if you have any questions.</h4>


<div class="contact-row row">
  <div class="col-xs-3 col-xs-offset-3 contact-column1" style="font-size: large;">
    <br>
    <br>
    <p>Phone: 1-800-find-friends</p>
    <p>Email: info@findfriends.com</p>
    <p>Fax: 100-000-000</p>
  </div>

  <div class="col-xs-3 contact-column">
    <br>
    <br>
    <form>
      <div class="form-group" id="full-name-input">
        <label class="control-label" for="inputSuccess1">Full Name</label>
        <input type="text" class="form-control" id="nameinput">
      </div>
      <div class="form-group " id="email-input">
        <label class="control-label" for="inputWarning1">Email</label>
        <input type="text" class="form-control" id="emailinput">
      </div>
      <div class="form-group " id="message-input">
        <label class="control-label" for="inputError1">Message</label>
        <textarea type="text" class="form-control" id="messageinput"></textarea>
      </div>

      <button type="submit" id="contactSubmitButton" class="btn btn-primary">Submit</button>
    </form>
  </div>

</div>



<script>
$('#contactSubmitButton').on('click', function() {
  alert("Thank you!");
});
</script>

app/views/static_pages/root.html.erb
<div class="backdrop">
  <div id="main" class="container">
  </div>
</div>

<script>
window.current_user_id = <%= current_user.id if current_user %>
</script>

app/views/users/index.html.erb
<div id="map-canvas">
</div>



<script type="application/json" id="bootstrapped_users_json">
    {"users": <%= @users.to_json.html_safe %> }
</script>

<script>
  users = JSON.parse($("#bootstrapped_users_json").html())["users"];

  function getLocation() {
      {
          if (navigator.geolocation)
          {
              var options = {
                  enableHighAccuracy: true,
                  timeout: 5000,
                  maximumAge: 0
              };
              navigator.geolocation.getCurrentPosition( success, error,options);
          }
          else
          { x.innerHTML= "Geolocation is not supported by this browser."; }
      }
  }

  function error(e) {
  console.log("error code:" + e.code + 'message: ' + e.message );
  }

  function success(position) {
     var  lat  = position.coords.latitude;
     var  lng =  position.coords.longitude;


     var  myLocation =   new google.maps.LatLng(lat, lng);

     var mapOptions = {
           center: new google.maps.LatLng(myLocation.lat(),myLocation.lng()),
          zoom: 13,
          mapTypeId: google.maps.MapTypeId.ROADMAP
     };

     var map = new google.maps.Map(document.getElementById("map-canvas"),
              mapOptions);

     var infowindow = new google.maps.InfoWindow({
        map: map,
        position: myLocation
      });

     var image = {
       url: 'http://www.pixeljoint.com/files/icons/full/cat__r177950541.gif',
       // This marker is 20 pixels wide by 32 pixels tall.
       size: new google.maps.Size(20, 32),
       // The origin for this image is 0,0.
       origin: new google.maps.Point(0,0),
       // The anchor for this image is the base of the flagpole at 0,32.
       anchor: new google.maps.Point(0, 32)
     };

     users.forEach(function(user) {
       var myLatLng = new google.maps.LatLng(user.lat, user.lng);

       if (id == user.id) {
         var marker = new google.maps.Marker({
             position: myLatLng,
             map: map,
             title:"me!",
             icon: image
         });

       } else {
        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title:"me!"
        });
       }

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.close();
          var content_string = '<div class="infowindow">' + user.email + '</div>'
          infowindow.setContent(content_string);
          infowindow.open(map, marker);
        });
      });
  }

  $(function() {
    getLocation();
    id = window.current_user_id;
  })

</script>

app/views/users/new.html.erb
<h1 class="signup-header">Sign Up</h1>



<div class= "sign-up-page">
<div class="sign-up">
<form action="<%= users_url %>"
      method="post"
      role="form"
      id="sign-up">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
<div class="form-group">
  <label for="user_email">Email &nbsp &nbsp &nbsp</label>
  <input
     id="user_email"
     name="user[email]"
     type="text"
     Placeholder="email"
     class="myclass">
  <br>
</div>
<div class="form-group">
  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password"
     Placeholder="password"
     class="myclass">
   </div>
  <br>

  <button type="submit" class="btn btn-success" role="button" id="sign-up-button">Sign Up</button>
</form>



 <form action="<%= session_url %>"
      method="post"
      role="form"
      id="sign-in-guest">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input name="user[email]" type="hidden" value="guestlogin">
  <input name="user[password]" type="hidden" value="guestlogin">
  <button type="submit" class="btn btn-primary" role="button" id="sign-in-guest-button">Guest Demo</button>
</form>
  <div class="sign-up-footer">
      Already a user?<a href="<%= new_session_url %>"> Sign In </a>
  </div>
</div>
</div>

app/views/users/show.html.erb
<br>
<br>
<br>
<br>
<br>

  <h1>Welcome to your profile page <%= User.find(params[:id]).email %>!</h1>

<!-- <h3> Your Friends </h3>
<br>
<br>
<ul class="users-list">
  <% @users.each do |user| %>
  <li class="user-email"> <%= user.email %> </li>
  <button class="btn btn-primary">Add Friend</button> 
  <br>
  <% end %>
</ul> -->